[package]
name = "strong-api-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
strong-api-lib = { path = "../strong-api-lib" }
dotenv = "0.15"
reqwest = "0.11"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }