[package]
name = "strong-api-data-dump"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.139"
dotenv = "0.15"
serde = { version = "1.0.218", features = ["derive"] }